services:
  - type: web
    name: evolution-api
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: chmod +x init-db.sh && ./init-db.sh
    envVars:
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: SERVER_URL
        value: https://evolution-api-z243.onrender.com
      - key: DATABASE_CONNECTION_URI
        sync: false
      - key: CACHE_REDIS_URI
        sync: false
      - key: AUTHENTICATION_API_KEY
        sync: false

